name: CD Frontend Pipeline

on:
  workflow_run:
    workflows: ["CD Backend Pipeline"]
    types:
      - completed

jobs:
  frontend-deploy:
    runs-on: [self-hosted, dockertest]

    steps:
    - name: Apagando Imagens não Usadas
      run:  docker image prune -a -f

    - name: Puxando a imagem docker
      run: sudo docker pull maathjason/garmspipeline-frontend:latest

    - name: Deletando o conteiner antigo
      run: sudo docker rm -f garmspipeline-frontend-container || true

    - name: Start container do frontend
      run: sudo docker run -d -p 80:80 -p 443:443 --name garmspipeline-frontend-container maathjason/garmspipeline-frontend:latest

      