name: CD Frontend Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline", "CD Backend Pipeline"]
    types:
      - completed

jobs:
  frontend-deploy:
    runs-on: [self-hosted, dockertest]

    steps:
    - name: Pull frontend Docker image
      run: sudo docker pull maathjason/garmspipeline-frontend:latest

    - name: Delete Old frontend container
      run: sudo docker rm -f garmspipeline-frontend-container || true

    - name: Start Frontend Container
      run: sudo docker run -d -p 80:80 --name garmspipeline-frontend-container maathjason/garmspipeline-frontend:latest
