name: CI Pipeline

on:
  push:
    branches: [ "test" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Criando .env para as credenciais
      run: |
        echo "DB_HOST=${{ secrets.DB_HOST }}" > back-end/.env
        echo "DB_USER=${{ secrets.DB_USER }}" >> back-end/.env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> back-end/.env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> back-end/.env

    - name: Login DockerHub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t maathjason/garmspipeline:latest .

    - name: Push to DockerHub
      run: docker push maathjason/garmspipeline:latest
