name: Pipeline

on: 
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-20.04
    steps:
  
      - name: Testando
        run: |
             echo "Hello World!"
             
      - name: Testando1.1
        run: |
             ping 192.16.3.23
