name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Testando
        run: |
          echo "Hello World!"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Use a versão LTS mais recente

      - name: Install dependencies
        run: |
          sudo apt update && echo "Sistema atualizado"
          sudo apt install nodejs npm && echo "Node.js instalado"
          sudo npm install && echo "Dependências baixadas"
