name: garms.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x] # Adicione aqui as versões do Node.js que você deseja testar

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Frontend Build
      run: |
        cd front-end
        npm install
        npm run build
        cd ..

    - name: Restart front e back
      run: |
        cd front-end
        pm2 reload garms || pm2 start npm --name garms -- start
        cd ../back-end
        pm2 reload backend || pm2 start server.js --name backend
        cd ..
        pm2 save

    - name: restart nginx
      run: |
        echo "${{ secrets.USER_PASS }}" | sudo -S service nginx restart
      env:
        USER_PASS: ${{ secrets.USER_PASS }}
