name: garms.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x] # Adicione aqui as versões do Node.js que você deseja testar

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: |
        npm i
        cd front-end
        npm i
        npm run build
        cd ..
        pm2 stop 0
        pm2 start 0
        pm2 save
         echo "${{ secrets.USER_PASSWORD }}" | sudo -S service nginx restart
