name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Testando
        run: |
          echo "Hello World!"
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Use a versão LTS mais recente

      - name: Install dependencies
        run: npm install axios semver

      - name: Download JavaScript and run tests
        run: |
          node -e "
          const axios = require('axios');

          const jsFileUrl = 'https://raw.githubusercontent.com/MuriloWeishaupt/API-GARMS/main/back-end/src/app.js';  // URL corrigida
          const expectedVersion = '1.0.0'; // Versão esperada

          async function downloadJavaScript() {
              try {
                  const response = await axios.get(jsFileUrl);
                  const scriptContent = response.data;

                  // Log do conteúdo do script para depuração
                  console.log('Conteúdo do script baixado:', scriptContent);

                  // Remover a verificação de versão ou definir a versão diretamente
                  console.log('A versão esperada é:', expectedVersion);
                  // Aqui você pode adicionar lógica para testar a funcionalidade do script se necessário

                  await testRequests();
              } catch (error) {
                  console.error('Erro ao baixar o arquivo JavaScript:', error);
                  process.exit(1); // Sair com erro
              }
          }

          async function testRequests() {
              try {
                  const response = await axios.get('https://api.example.com/endpoint');
                  console.log('Resposta da requisição:', response.data);
              } catch (error) {
                  console.error('Erro ao realizar requisição:', error);
                  process.exit(1); // Sair com erro
              }
          }

          downloadJavaScript();
          "
