name: garms.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x] # Adicione aqui as versões do Node.js que você deseja testar

    steps:
    - uses: actions/checkout@v3

    - name: Instalando Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}


    - name: Criando .env para as credenciais 
      run: |
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> back-end/.env
        echo "DB_USER=${{ secrets.DB_USER }}" >> back-end/.env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> back-end/.env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> back-end/.env


    - name: Build do Front-End
      run: |
        npm i
        npm update
        cd front-end
        npm install
        npm run build
        cd ..

    - name: Instalando dependências do Back-end
      run: |
        cd back-end
        npm i
        npm update
        npm install cors

    - name: Test Backend
      run: |
        cd back-end
        npm test

    - name: Resetando front e back
      run: |
        cd ../front-end
        pm2 reload garms || pm2 start npm --name garms -- npm run dev
        cd ../back-end
        pm2 reload backend || pm2 start --name backend -- npm run dev
        cd ..
        pm2 save
        
#- name: restart nginx
#      run: |
#        echo "${{ secrets.USER_PASS }}" | sudo -S service nginx restart
#      env:
#        USER_PASS: ${{ secrets.USER_PASS }}
 
