name: garms.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Adicione aqui as versões do Node.js que você deseja testar

    steps:
    - uses: actions/checkout@v3

    - name: Instalando Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}


    - name: Teste Mocha BackEnd
      run: |
        npm ci
        npm update
        cd back-end
        npm run test