name: garmsTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Adicione aqui as versões do Node.js que você deseja testar

    steps:
    - uses: actions/checkout@v3

    - name: Instalando Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}


    - name: Criando .env para as credenciais
      run: |
        echo "DB_HOST=${{ secrets.DB_HOST }}" > back-end/.env
        echo "DB_USER=${{ secrets.DB_USER }}" >> back-end/.env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> back-end/.env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> back-end/.env
        
    - name: Teste Mocha BackEnd
      run: |
        npm i
        cd back-end
        npm i
        npm ci
        npm update
        npm run test
